import "@/styles/globals.css";

import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { Client } from "./client";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <Client>{children}</Client>
        </Providers>
      </body>
    </html>
  );
}
